config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    resources :comments 
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, :body, presence: true

    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :comments

    scope :published, -> { where.not(published_at: nil) }
    scope :draft, -> { where(published_at: nil) }
    scope :recent, -> { where('articles.published_at > ?', 1.week.ago.to_date) }
    scope :where_title, -> (term) { where("articles.title LIKE ?", "%#{term}%") }

    def long_title
        "#{title} - #{published_at}"
    end

    def published?
        published_at.present?
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :articles

    default_scope { order :name }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article

    validates :name, :email, :body, presence: true
    validates :article_should_be_published

    def article_should_be_published
        errors.add(:article_id, 'is not published yet') if article && !article.published?
    end

    def email_article_author 
        puts "We will notify #{article.user.email} in Chapter 12"
    end 
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord
    attr_accessor :password 

    validates :email, uniqueness: true 
    validates :email, length: { in: 5..50 }
    validates :email, format: { with: /\A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}\z/i }
    validates :password, confirmation: true, if: :password_required?
    validates :password, length: { in: 4..20 }, if: :password_required?
    validates :password, presence: true, if: :password_required?

    has_one :profile
    has_many :articles, -> { order 'published_at DESC, title ASC' },
            dependent: :nullify
    has_many :replies, through: :articles, source: :comments

    before_save :encrypt_new_password

    def self.authenticate(email, password)
        user = find_by email: email
        return user if user && user.authenticated?(password)
    end

    def authenticated?(password)
        self.hashed_password == encrypt(password)
    end

    protected 

    def encrypt_new_password
        return if password.blank?
        self.hashed_password = encrypt(password)
    end

    def password_required?
        hashed_password.blank? || password.present?
    end 

    def encrypt(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :location, :excerpt, :body, :published_at)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :load_article

    def create
        @comment = @article.comments.new(comment_params)
        if @comment.save
            redirect_to @article, notice: 'Thank you for your comment'
        else 
            redirect_to @article, alert: 'Unable to add comment'
        end 
    end 

    def destroy 
        @comment = @article.comments.find(params[:id])
        @comment.destroy 
        redirect_to @article, notice: 'Comment deleted'
    end 

    private 
    
    def load_article 
        @article = Article.find(params[:article_id])
    end 
    
    def comment_params 
        params.require(:comment).permit(:name, :email, :body)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            redirect_to articles_path, notice: 'User succesfully added.'
        else 
            render action: :new
        end 
    end

    def edit
    end

    def update 
        if @user.update(user_params)
            redirect_to articles_path, notice: 'Updated user information succesfully.'
        else 
            render action: 'edit'
        end 
    end 

    private 
    def set_user 
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :excerpt %>
    <%= form.text_field :excerpt %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Excerpt</th>
      <th>Body</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.location %></td>
        <td><%= article.excerpt %></td>
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>

<h3>Comments</h3>
<div id="comments">
  <%= render @article.comments %>
</div>

<%= render 'comments/new' %>

app/views/comments/_comment.html.erb
<div class="comment"> 
    <h3>
        <%= comment.name %> <<%= comment.email %>> said: 
        <span class="actions">
            <%= link_to 'Delete', article_comment_path(article_id: @article, id: comment), 
            confirm: 'Are you sure?', method: :delete %>
        </span>
    </h3>
    <%= comment.body %>
</div>

app/views/comments/_new.html.erb
<%= form_with(model: @article.comments.new, url: article_comments_path 
(@article), local: true) do |form| %>
    <div class="field">
        <%= form.label :name %><br />
        <%= form.text_field :name %>
    </div>
    <div class="field">
        <%= form.label :email %><br />
        <%= form.text_area :body %>
    </div>
    <div class="actions">
        <%= form.submit 'Add' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_tag :p, notice, class: 'notice' if notice.present? %>
    <%= content_tag :p, notice, class: 'alert' if alert.present? %>
    
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralise(user.errors.count, "error") %> prohibited his user from being saved:</h2>     

            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>

    <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', articles_path %>